---
- hosts: all
  become: true
  pre_tasks:
    - name: updated repo cache (CentOS)
      tags: always
      dnf:
        update_cache: yes
      changed_when: false
      when: ansible_distribution == "CentOS"

    - name: update repo cache (Ubuntu)
      tags: always
      apt:
        upgrade: safe
        update_cache: yes
      changed_when: false
      when: ansible_distribution == "Ubuntu" or ansible_distribution == "Debian"

- hosts: all
  become: true
  tasks:
    - name: add ssh key for simone
      tags: always
      authorized_key:
        user: simone
        key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPBVNUT17Dh4iSK7VKPcBEq7TUGHiOnPLsZgMPEz+C+E ansible"

- hosts: workstations
  become: true
  tasks:
    - name: install unzip
      tags: unzip
      package:
        name: unzip
        state: latest

    - name: install terraform
      unarchive:
        src: https://releases.hashicorp.com/terraform/1.10.4/terraform_1.10.4_linux_amd64.zip
        dest: /usr/local/bin
        remote_src: yes
        mode: 0755
        owner: root
        group: root

- hosts: web-servers
  become: true
  tasks:
    - name: install httpd package (CentOS)
      tags: httpd,apache,centos
      dnf:
        name:
          - httpd
          - php
        state: latest
      when: ansible_distribution == "CentOS"

    - name: install apache2 package (Ubuntu,Debian)
      tags: apache,apache2,ubuntu,debian
      apt:
        name:
          - apache2
          - libapache2-mod-php
        state: latest
      when: ansible_distribution == "Ubuntu" or ansible_distribution == "Debian"

    - name: start httpd (CentOS)
      tags: httpd,apache,centos
      service:
        name: httpd
        state: started
        enabled: true
      when: ansible_distribution == "CentOS"

    - name: start apache2 (Ubuntu, Debian)
      tags: apache,apache2, ubuntu, debian
      service:
        name: apache2
        state: started
        enabled: true
      when: ansible_distribution == "Ubuntu" or ansible_distribution == "Debian"

    - name: change e-mail addres for admin
      tags: apache, apache2, httpd
      lineinfile:
        path: /etc/httpd/conf/httpd.conf
        regexp: "^ServerAdmin"
        line: "ServerAdmin 123@example.com"
        state: present
      when: ansible_distribution == "CentOS" or ansible_distribution == "Ubuntu" or ansible_distribution == "Debian"
      register: httpd

    - name: start httpd (centos)
      tags: httpd,apache,centos
      service:
        name: httpd
        state: restarted
      when: httpd.changed

    - name: copy default html file for site
      tags: apache, apache2, httpd
      copy:
        src: default_site.html
        dest: /var/www/html/index.html
        owner: root
        group: root
        mode: 0644

- hosts: db_servers
  become: true
  tasks:
    - name: install mariadb server package (CentOS)
      tags: centos,db,mariadb
      dnf:
        name: mariadb
        state: latest
      when: ansible_distribution == "CentOS"

    - name: install mariadb server (Ubuntu,Debian)
      tags: db,mariadb,ubuntu,debian
      apt:
        name: mariadb-server
        state: latest
      when: ansible_distribution == "Ubuntu" or ansible_distribution == "Debian"

- hosts: file_servers
  become: true
  tasks:
    - name: install samba package
      tags: samba
      package:
        name: samba
        state: latest
