- name: add ssh key for simone
  authorized_key:
    user: simone
    key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPBVNUT17Dh4iSK7VKPcBEq7TUGHiOnPLsZgMPEz+C+E ansible"

- name: generate sshd_config file from template
  tags: ssh
  template:
    src: "{{ ssh_template_file }}"
    dest: /etc/ssh/sshd_config
    mode: 0644
    owner: root
    group: root
  notify: restart_sshd
